development:
  dialect: postgres
  datasource: dbname=simplefitness sslmode=disable
  dir: migrations

production:
  dialect: postgres
  datasource: dbname=simplefitness sslmode=disable
  dir: migrations